spring.application.name=facade
spring.datasource.url=jdbc:hsqldb:hsql://localhost/xdb
spring.datasource.driverClassName=org.hsqldb.jdbc.JDBCDriver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update